
\c cs415

CREATE TABLE WebUser (
  web_user_id INT GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR(25) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  email VARCHAR(40)  UNIQUE NOT NULL,
  password VARCHAR(40) NOT NULL,
  created_date TIMESTAMP DEFAULT NULL,
  is_active BOOLEAN DEFAULT true,
  last_login TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (web_user_id)
);

CREATE TABLE UserInfo (
    user_info_id INT GENERATED BY DEFAULT AS IDENTITY,
    web_user_id INT,
    profile_bio VARCHAR(500),
    profile_picture VARCHAR(150),
    modified_date TIMESTAMP,
    created_date TIMESTAMP,
    PRIMARY KEY (user_info_id),
    FOREIGN KEY (web_user_id) REFERENCES WebUser(web_user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE PhoneType (
    phone_type_id INT GENERATED BY DEFAULT AS IDENTITY,
    phone_type VARCHAR(10),
    PRIMARY KEY (phone_type_id)
);

CREATE TABLE UserPhone (
    user_phone_id INT GENERATED BY DEFAULT AS IDENTITY,
    phone_type_id INT,
    phone_number VARCHAR(10),
    created_date TIMESTAMP,
    is_active BOOLEAN,
    web_user_id INT,
    PRIMARY KEY (user_phone_id),
    FOREIGN KEY (phone_type_id) REFERENCES PhoneType(phone_type_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    FOREIGN KEY (web_user_id) REFERENCES WebUser(web_user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE AddressType (
    address_type_id INT GENERATED BY DEFAULT AS IDENTITY,
    address_type VARCHAR(20) NOT NULL,
    PRIMARY KEY (address_type_id)
);

CREATE TABLE UserAddress (
    user_address_id INT GENERATED BY DEFAULT AS IDENTITY,
    web_user_id INT NOT NULL,
    street_1 VARCHAR(50),
    street_2 VARCHAR(50),
    city VARCHAR(35),
    st VARCHAR(2),
    zip VARCHAR(10),
    country VARCHAR(30),
    created_date TIMESTAMP,
    address_type_id INT NOT NULL,
    PRIMARY KEY (user_address_id),
    FOREIGN KEY (web_user_id ) REFERENCES WebUser(web_user_id )
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    FOREIGN KEY (address_type_id) REFERENCES AddressType(address_type_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE PageData (
    page_data_id INT GENERATED BY DEFAULT AS IDENTITY,
    page_name VARCHAR(150),
    page_title VARCHAR(150),
    page_description text,
    page_picture VARCHAR(250),
    page_menu VARCHAR(55)
);
